global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-2
        access_key: 'AKIA3B7ZPPCU5P4OEDHT'
        secret_key: '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'
        port: 9100
